config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'computers#index'
  resources :static_pages
  resources :computers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computer.rb
class Computer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
	def index
		@computers = Computer.all
  end

  def new
  	@computer = Computer.new
  end

  def create
    Computer.create(computer_params)
    redirect_to computers_path
  end

  private

  def computer_params
    params.require(:computer).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/computers/index.html.erb
<br /><br />
<h1>Computers</h1>
<br />
<% @computers.each do |computer| %>
  <div class="booyah-box col-10 offset-1">
    <h4><%= computer.name %></h4><br />
    <p><%= computer.description %></p><br />
  </div>
<% end %>

<br />
<br /><br />

app/views/computers/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Computer Details</h1>
  <%= simple_form_for @computer do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wow</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Home', computers_path, class: 'Gaming' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_computer_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Build
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>